batch_size: 32  # The batch size to use during data loading

image_transform:
  resize: [224, 224]  # Resize images to 224x224 pixels
  grayscale: 3  # Convert images to grayscale with 3 channels
  normalize_mean: [0.485, 0.456, 0.406]  # Normalization mean values for RGB channels
  normalize_std: [0.229, 0.224, 0.225]  # Normalization std values for RGB channels


#change nothing here